server:
  port: 8082


dubbo:
  application:
    name: shop_back_consumer
  registry:
    address: zookeeper://192.168.235.160:2181
  protocol:
    port: -1
  consumer:
    check: false

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB

fdfs:
  tracker-list: 192.168.235.160:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  serverpath: http://192.168.235.160/