spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.235.160
    username: root
    password: root
    virtual-host: /root
    port: 5672
dubbo:
  application:
    name: shop_goods_service
  registry:
    address: zookeeper://192.168.235.160:2181
  protocol:
    port: -1
  consumer:
    check: false
  provider:
    timeout: 10000

server:
  port: 8084
